apiVersion: configmanagement.gke.io/v1
kind: ClusterSelector
metadata:
  name: cluster-prd-1-selector
spec:
  selector:
    matchLabels:
      location: northamerica-east1
      type: apps
---
apiVersion: configmanagement.gke.io/v1
kind: ClusterSelector
metadata:
  name: cluster-prd-2-selector
spec:
  selector:
    matchLabels:
      location: northamerica-east2
      type: apps
---
kind: Cluster
apiVersion: clusterregistry.k8s.io/v1alpha1
metadata:
  name: gke-cls-prd-1
  labels:
    location: northamerica-east1
    type: apps
---
kind: Cluster
apiVersion: clusterregistry.k8s.io/v1alpha1
metadata:
  name: gke-cls-prd-2
  labels:
    location: northamerica-east2
    type: apps
